name: Deploy to remote

on:
  push:
    branches: [main]

jobs:
  create-depeloyment-artifacts:
    name: Create deployment artifacts
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v4

      - name: Create CSS and Javascript
        run: |
          npm install
          npm run build

      - name: Configure PHP 8.2
        uses: shivammathur/setup-php@v2
        with:
          php-version: "8.2"
          extensions: mbstring, ctype, fileinfo, openssl, PDO, bcmath, json, tokenizer, xml

      - name: Install composer dependencies
        run: composer install --prefer-dist --no-dev --no-interaction

      - name: Add storage link
        run: php artisan storage:link

      - name: Create deployment artifact
        env:
          GITHUB_SHA: ${{ github.sha }}
        run: tar -czf "${GITHUB_SHA}".tar.gz --exclude=*.git *

      - name: Store artifact for distribution
        uses: actions/upload-artifact@v4
        with:
          name: app-build
          path: ${{ github.sha }}.tar.gz
          
